export const setoresDeAtuacao = [
  {
    id: 0,
    value: 'Alimentos e bebidas',
    sub: [
      'Açúcar e álcool',
      'Adubos e fertilizantes',
      'Água mineral e refrigerantes',
      'Animais vivos',
      'Bebidas destiladas',
      'Cacau e produtos de confeitaria',
      'Café',
      'Carne Bovina',
      'Carnes de Aves',
      'Carne Suína',
      'Demais carnes',
      'Cereais',
      'Cerveja',
      'Chá mate e especiarias',
      'Chocolates',
      'balas e confeitos',
      'Outros açúcares',
      'Farinhas para animais',
      'Fornecimento de alimentação e bebidas',
      'Frutas',
      'Fumo e cigarro',
      'Gorduras e óleo animais e vegetais',
      'Leite',
      'Laticínios',
      'ovos e mel',
      'Massa alimentícias e preparação de alimentos',
      'Outros produtos de origem animal',
      'Peixes e crustáceos',
      'Preparação de carnes',
      'peixes e crustáceos',
      'Produtos hortícolas e plantas vivas',
      'Produtos químicos',
      'Sementes oleaginosas (exceto soja)',
      'Soja (grão',
      'óleo e farelo)',
      'Sucos',
      'Vinhos',
      'Vermute e vinagre',
    ],
  },
  {
    id: 1,
    value: 'Casa e construção',
    sub: [
      'Artesanato',
      'Artesanato de materiais não-ferrosos',
      'Ferramentas',
      'Talheres e outras obras de metais',
      'Madeiras',
      'Cortiças e obras de trançaria',
      'Materiais não-ferrosos',
      'Móveis',
      'Obras de pedra e semelhantes',
      'Obras diversas',
      'Produtos cerâmicos',
      'Produtos de limpeza',
      'Produtos minerais',
      'Tintas',
      'Vidro e suas obras',
    ],
  },
  {
    id: 2,
    value: 'Entretenimentos e serviços',
    sub: [
      'Brinquedos',
      'Cessão de direitos de propriedade intelectual',
      'Instrumentos musicais',
      'Obras de arte',
      'Serviços de apoio às atividades empresariais – Publicidade e Propaganda',
      'Serviço de Construção',
      'Serviço de despachante aduaneiro',
      'Serviço de manutenção',
      'reparação e instalação (exceto construção)',
      'Serviço de Publicidade',
      'Impressão e reprodução',
      'Serviço de tratamento',
      'Eliminação e coleta de resíduo sólidos saneamento',
      'Serviços educacionais',
      'Serviços financeiros e relacionados',
      'Serviços imobiliários',
      'Serviços jurídicos e contábeis',
      'Serviços pessoais',
      'Serviços postais',
      'Serviços recreativos culturais e desportivos – Cinema',
      'Serviços recreativos culturais e desportivos – Conteúdos',
      'Serviços recreativos culturais e desportivos - Música',
      'Arrendamento mercantil e operacional',
      'Propriedade intelectual',
      'Franquias',
    ],
  },
  {
    id: 3,
    value: 'Máquinas e equipamentos',
    sub: [
      'Aviões e suas partes',
      'Armas e munições',
      'Borracha e suas obras',
      'Embarcações',
      'Equipamentos médicos-odontológicos',
      'Impressos',
      'Instrumentos de precisão',
      'Máquinas  e motores',
      'Materiais elétricos e eletroeletrônicos',
      'Papel e celulose',
      'Petróleo e derivados de petróleo',
      'Plástico e suas obras',
      'Pólvora',
      'Produtos metalúrgicos e fundição',
      'Serviço de apoio aos transportes',
      'Serviços de apoio a atividade agropecuárias',
      'Extrativismo mineral',
      'Eletricidade',
      'Serviço de transmissão de eletricidade',
      'Serviços de transmissão de gás',
      'Serviços de transporte de cargas',
      'Serviços de transporte de passageiros',
    ],
  },
  {
    id: 4,
    value: 'Moda',
    sub: [
      'Calçados e suas partes',
      'Colas e enzimas',
      'Higiene pessoal e cosméticos',
      'Joias',
      'Bijuterias',
      'Metais e pedras preciosas',
      'Peles',
      'Peleterias e couro e seus artefatos',
      'Têxteis',
      'Aparelhos de relojoarias',
    ],
  },
  {
    id: 5,
    value: 'Tecnologia',
    sub: [
      'Biotecnologia',
      'Produtos farmacêuticos',
      'Produtos para fotografia',
      'Serviços de pesquisa e desenvolvimento',
      'Serviços de tecnologia da informação',
      'Serviços de telecomunicação',
      'Difusão e fornecimento de informações',
      'Serviços relacionados a saúde humana e de assistência social',
    ],
  },
]
